// Catálogo DEMO de TurisClick V2: atractivos reales de Bolivia operados por proveedores FICTICIOS.
// Precios en BOB de referencia para la demo (no son tarifas reales). Fuentes de la investigación en README.md.
//
// Reglas que el loader verifica antes de tocar la API:
// - cada experiencia está en una ciudad de la zona de su proveedor;
// - cada paquete sólo referencia experiencias del mismo proveedor;
// - toda experiencia/paquete tiene imágenes resueltas en images.manifest.json (con licencia y autor).

export const CAT = {
  AV: 'Aventura',
  CU: 'Cultura',
  GA: 'Gastronomía',
  HI: 'Historia',
  NA: 'Naturaleza',
  RB: 'Relax y bienestar',
}

// Ciudades que no existían en el seed y que el pedido nombra explícitamente. Se crean como CITY bajo su
// departamento real, vía POST /api/admin/destinations. Chiquitos no es una ciudad: se usa San Ignacio de Velasco.
export const NEW_CITIES = [
  { name: 'Copacabana', region: 'La Paz' },
  { name: 'Coroico', region: 'La Paz' },
  { name: 'Rurrenabaque', region: 'El Beni' },
  { name: 'Samaipata', region: 'Santa Cruz' },
  { name: 'Torotoro', region: 'Potosí' },
]

// passwordEnv: variable de entorno con la contraseña (la pone run-catalog.ps1 desde DPAPI; nunca en el repo).
export const PROVIDERS = [
  {
    key: 'altura',
    email: 'proveedor.demo@turisclick.dev', // cuenta demo previa, reutilizada y renombrada
    passwordEnv: 'PROVIDER_PASSWORD',
    firstName: 'Carla', lastName: 'Mamani',
    companyName: 'Altura Viva Expediciones',
    legalDocument: 'NIT-DEMO-1020304',
    contactEmail: 'contacto.demo@turisclick.dev',
    description: 'Operador receptivo (ficticio, cuenta de demostración) del altiplano: La Paz, El Alto, Oruro y el Salar de Uyuni.',
    zone: ['La Paz', 'El Alto', 'Oruro', 'Uyuni'],
  },
  {
    key: 'lagoyungas',
    email: 'proveedor.lagoyungas@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Rolando', lastName: 'Quispe',
    companyName: 'Lago y Yunga Senderos',
    legalDocument: 'NIT-DEMO-2030405',
    contactEmail: 'lagoyungas.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) del Lago Titicaca y los Yungas: Copacabana, Isla del Sol y Coroico.',
    zone: ['Copacabana', 'Coroico'],
  },
  {
    key: 'surandino',
    email: 'proveedor.surandino@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Marcelo', lastName: 'Choque',
    companyName: 'Quebrada Roja Andina',
    legalDocument: 'NIT-DEMO-3040506',
    contactEmail: 'surandino.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) del sur andino: la Villa Imperial de Potosí y las quebradas de Tupiza.',
    zone: ['Potosí', 'Tupiza'],
  },
  {
    key: 'llajta',
    email: 'proveedor.llajta@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Verónica', lastName: 'Rojas',
    companyName: 'Llajta Verde Aventura',
    legalDocument: 'NIT-DEMO-4050607',
    contactEmail: 'llajta.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) del valle y el trópico de Cochabamba, con salidas a Torotoro.',
    zone: ['Cochabamba', 'Quillacollo', 'Sipe Sipe', 'Tiquipaya', 'Villa Tunari', 'Torotoro'],
  },
  {
    key: 'charcas',
    email: 'proveedor.charcas@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Gabriela', lastName: 'Arancibia',
    companyName: 'Charcas Patrimonio Vivo',
    legalDocument: 'NIT-DEMO-5060708',
    contactEmail: 'charcas.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) de Sucre y sus alrededores: patrimonio colonial, Cal Orck\'o y Maragua.',
    zone: ['Sucre'],
  },
  {
    key: 'chapaca',
    email: 'proveedor.chapaca@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Esteban', lastName: 'Baldiviezo',
    companyName: 'Cepa Chapaca Rutas',
    legalDocument: 'NIT-DEMO-6070809',
    contactEmail: 'chapaca.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) de Tarija y el Chaco tarijeño: vino de altura, cascadas y reservas naturales.',
    zone: ['Tarija', 'Bermejo', 'Villamontes'],
  },
  {
    key: 'curichi',
    email: 'proveedor.curichi@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Daniela', lastName: 'Suárez',
    companyName: 'Curichi Oriente Travesías',
    legalDocument: 'NIT-DEMO-7080910',
    contactEmail: 'curichi.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) del oriente cruceño: Santa Cruz, Samaipata, Amboró y las misiones de Chiquitos.',
    zone: ['Santa Cruz de la Sierra', 'Cotoca', 'Santiago del Torno', 'Samaipata', 'San Ignacio de Velasco'],
  },
  {
    key: 'jichi',
    email: 'proveedor.jichi@turisclick.dev',
    passwordEnv: 'CATALOG_PROVIDER_PASSWORD',
    firstName: 'Tomás', lastName: 'Vaca',
    companyName: 'Jichi Amazonía Expediciones',
    legalDocument: 'NIT-DEMO-8091011',
    contactEmail: 'jichi.demo@turisclick.dev',
    description: 'Operador (ficticio, cuenta de demostración) de la Amazonía boliviana: Rurrenabaque, Madidi, Trinidad y Riberalta.',
    zone: ['Rurrenabaque', 'Trinidad', 'Riberalta'],
  },
]

// Datos que el pedido pide limpiar: se retiran del catálogo público SIN borrar (no hay DELETE en la API).
export const LEGACY = {
  unpublishExperiences: [{ provider: 'altura', title: 'Sucre colonial: centro histórico' }],
  suspendUsers: ['qa.turista@turisclick.dev'],
  demoTourist: { email: 'turista.demo@turisclick.dev', firstName: 'Lucía', lastName: 'Fernández', passwordEnv: 'DEMO_TOURIST_PASSWORD' },
}

// weekdays: 0 = domingo … 6 = sábado (sólo se generan fechas en esos días). Sin weekdays, cualquier día.
// img: búsquedas en Wikimedia Commons; files: archivos fijados a mano (tienen prioridad).
const INC_GUIDE = 'Guía local en español, entradas indicadas en la descripción.'
export const EXPERIENCES = [
  // ───────────────────────── La Paz y El Alto (Altura Viva) ─────────────────────────
  {
    key: 'lpz-teleferico', provider: 'altura', city: 'La Paz', cats: ['CU'],
    title: 'La Paz desde el Teleférico',
    description: 'Recorrido por las líneas de Mi Teleférico, la red de cabinas que une La Paz y El Alto. Cruzamos la ciudad por el aire desde la zona Sur hasta el borde del altiplano, con paradas en miradores para entender cómo La Paz se acomoda en su valle, con el Illimani de fondo.',
    includes: 'Guía, pasajes de teleférico del recorrido.', excludes: 'Comidas y bebidas.',
    minutes: 240, label: 'Medio día', price: 180, start: '09:30:00', slots: 15,
    files: ['File:Teleférico La Paz - El Alto Bolivia 43.jpg', 'File:Teleférico La Paz - El Alto Bolivia 42.jpg'],
  },
  {
    key: 'lpz-valle-luna', provider: 'altura', city: 'La Paz', cats: ['NA'],
    title: 'Caminata por el Valle de la Luna',
    description: 'Sendero corto entre las formaciones de arcilla erosionadas por la lluvia en Mallasa, al sur de La Paz. Un paseo tranquilo de paisaje casi lunar, ideal para la primera tarde de aclimatación en la ciudad.',
    includes: 'Guía, transporte ida y vuelta desde el centro, entrada al sendero.', excludes: 'Comidas.',
    minutes: 180, label: '3 horas', price: 120, start: '14:00:00', slots: 10,
    files: ['File:03-Valle de la Luna (La Paz)-3.jpg', 'File:03-Valle de la Luna (La Paz)-5.jpg'],
  },
  {
    key: 'lpz-tiwanaku', provider: 'altura', city: 'La Paz', cats: ['HI', 'CU'],
    title: 'Tiwanaku y la Puerta del Sol: día arqueológico',
    description: 'Excursión al sitio de Tiwanaku, Patrimonio de la Humanidad, a unos 70 km de La Paz. Visitamos la pirámide de Akapana, el templo de Kalasasaya con la Puerta del Sol, el templete semisubterráneo y los museos del sitio, que guardan monolitos y cerámica de una de las culturas más influyentes de los Andes.',
    includes: 'Transporte, guía, entradas a sitio y museos, almuerzo.', excludes: 'Propinas.',
    minutes: 480, label: 'Día completo', price: 380, start: '08:00:00', slots: 16,
    img: ['Tiwanaku Puerta del Sol', 'Kalasasaya Tiwanaku'],
  },
  {
    key: 'lpz-chacaltaya', provider: 'altura', city: 'La Paz', cats: ['AV', 'NA'],
    title: 'Chacaltaya a 5.300 m y el Valle de las Ánimas',
    description: 'Subida en vehículo hasta la antigua estación de esquí del Chacaltaya y caminata corta a su cumbre, con vista a la Cordillera Real, el Huayna Potosí y el lago Titicaca en días despejados. De regreso paramos en el Valle de las Ánimas, un bosque de agujas de arcilla. Requiere estar aclimatado a la altura.',
    includes: 'Transporte, guía, entradas, refrigerio.', excludes: 'Ropa de abrigo (recomendada).',
    minutes: 420, label: '7 horas', price: 320, start: '08:30:00', slots: 12,
    img: ['Chacaltaya', 'Valle de las Animas La Paz'],
  },
  {
    key: 'lpz-yungas-bici', provider: 'altura', city: 'La Paz', cats: ['AV'],
    title: 'Camino a los Yungas en bicicleta de montaña',
    description: 'Descenso en bicicleta por la antigua carretera a los Yungas, conocida como el “camino de la muerte”, hoy casi sin tráfico. Bajamos desde La Cumbre, a más de 4.600 m, hasta el bosque subtropical de Yolosa: más de 3.000 metros de desnivel en un día, con guía y vehículo de apoyo todo el trayecto.',
    includes: 'Bicicleta doble suspensión, casco y protecciones, guía, vehículo de apoyo, almuerzo y retorno a La Paz.', excludes: 'Seguro personal de viaje.',
    minutes: 660, label: 'Día completo', price: 780, start: '07:00:00', slots: 12,
    img: ['North Yungas Road', 'Yungas road Bolivia'],
  },
  {
    key: 'lpz-calle-jaen', provider: 'altura', city: 'La Paz', cats: ['HI', 'CU'],
    title: 'Calle Jaén y los museos del casco colonial',
    description: 'La calle colonial mejor conservada de La Paz, empedrada y con casonas de balcones de colores. Recorremos los museos municipales que funcionan en sus casas, como el de Metales Preciosos, el Costumbrista y el del Litoral Boliviano, y terminamos en la Casa de Murillo.',
    includes: `${INC_GUIDE} Entradas a los museos municipales.`, excludes: 'Transporte.',
    minutes: 180, label: '3 horas', price: 130, start: '10:00:00', slots: 15,
    weekdays: [2, 3, 4, 5, 6, 0],
    img: ['Calle Jaén La Paz'],
  },
  {
    key: 'lpz-casco-historico', provider: 'altura', city: 'La Paz', cats: ['HI', 'CU'],
    title: 'Plaza Murillo, San Francisco y el Mercado de las Brujas',
    description: 'Caminata por el centro histórico de La Paz: la Plaza Murillo con la Catedral y el Palacio de Gobierno, la Basílica de San Francisco con su fachada de estilo barroco mestizo y las calles Sagárnaga y Linares, donde el mercado de las brujas vende amuletos y ofrendas para la Pachamama.',
    includes: INC_GUIDE, excludes: 'Entrada al museo de San Francisco (opcional), compras.',
    minutes: 180, label: '3 horas', price: 110, start: '15:00:00', slots: 20,
    img: ['Basílica de San Francisco La Paz', 'Plaza Murillo La Paz'],
  },
  {
    key: 'lpz-mercados', provider: 'altura', city: 'La Paz', cats: ['GA', 'CU'],
    title: 'Mercados paceños y sabores de la ciudad',
    description: 'Una mañana de mercado para probar La Paz: salteñas recién horneadas, frutas de los Yungas, variedades de papa y chuño del altiplano y un api con pastel. Visitamos el Mercado Rodríguez y el Mercado Lanza con degustaciones en puestos tradicionales.',
    includes: 'Guía, degustaciones incluidas en el recorrido.', excludes: 'Compras personales.',
    minutes: 210, label: '3 h 30 min', price: 220, start: '09:00:00', slots: 10,
    img: ['Mercado Rodríguez La Paz', 'Salteña Bolivia'],
  },
  {
    key: 'lpz-muela-diablo', provider: 'altura', city: 'La Paz', cats: ['AV', 'NA'],
    title: 'Muela del Diablo: trekking con vista al valle',
    description: 'Caminata desde la zona Sur hasta la base de la Muela del Diablo, un antiguo cuello volcánico que se eleva sobre el valle de La Paz. El sendero pasa por comunidades de la periferia y regala una de las mejores vistas del Illimani.',
    includes: 'Transporte al inicio del sendero, guía, refrigerio.', excludes: 'Calzado de trekking.',
    minutes: 300, label: '5 horas', price: 200, start: '08:30:00', slots: 10,
    img: ['Muela del Diablo La Paz'],
  },
  {
    key: 'lpz-huayna-potosi', provider: 'altura', city: 'La Paz', cats: ['AV', 'NA'],
    title: 'Huayna Potosí: jornada de iniciación en glaciar',
    description: 'Día de introducción a la montaña en el glaciar del Huayna Potosí (6.088 m). Desde el campo base practicamos uso de crampones, piolet y cuerda con guías de alta montaña, sin intentar la cumbre. Pensado para quienes ya están aclimatados y quieren conocer el hielo de la Cordillera Real.',
    includes: 'Transporte, guía de montaña, equipo técnico, almuerzo.', excludes: 'Ropa técnica personal.',
    minutes: 600, label: 'Día completo', price: 650, start: '06:00:00', slots: 8,
    img: ['Huayna Potosí'],
  },
  {
    key: 'lpz-cocina-andina', provider: 'altura', city: 'La Paz', cats: ['GA'],
    title: 'Cena de cocina andina con productos del altiplano',
    description: 'Cena de pasos pensada alrededor de productos de los Andes bolivianos: quinua real, trucha del Titicaca, papas nativas, chuño y ají. Cada plato se presenta con su origen y la forma en que se consume en las comunidades del altiplano.',
    includes: 'Menú de degustación y bebida sin alcohol.', excludes: 'Bebidas alcohólicas, transporte.',
    minutes: 150, label: '2 h 30 min', price: 280, start: '19:30:00', slots: 12,
    img: ['Quinoa real Bolivia', 'Chuño'],
  },
  {
    key: 'elalto-feria', provider: 'altura', city: 'El Alto', cats: ['CU'],
    title: 'Feria 16 de Julio y los cholets de El Alto',
    description: 'Recorrido por la Feria 16 de Julio de El Alto, uno de los mercados callejeros más grandes de Bolivia, que funciona los jueves y domingos. Terminamos mirando los cholets, los edificios de fachadas coloridas que se volvieron símbolo de la arquitectura aymara contemporánea.',
    includes: 'Guía, pasajes de teleférico ida y vuelta.', excludes: 'Compras y comidas.',
    minutes: 240, label: 'Medio día', price: 170, start: '10:00:00', slots: 10,
    weekdays: [4, 0],
    img: ['El Alto 16 de Julio feria', 'Cholet El Alto'],
  },

  // ───────────────────────── Oruro (Altura Viva) ─────────────────────────
  {
    key: 'oru-socavon', provider: 'altura', city: 'Oruro', cats: ['HI', 'CU'],
    title: 'Santuario del Socavón y museo minero de Oruro',
    description: 'Visita al Santuario de la Virgen del Socavón, centro del Carnaval de Oruro (Obra Maestra del Patrimonio Oral e Inmaterial de la Humanidad), y al museo minero que funciona en una antigua galería bajo el templo, donde se cuenta la historia minera de la ciudad y la figura del Tío.',
    includes: `${INC_GUIDE} Entrada al museo.`, excludes: 'Transporte desde otras ciudades.',
    minutes: 180, label: '3 horas', price: 110, start: '10:00:00', slots: 20,
    files: ["File:Santuario de Nuestra Señora del Socavón, Oruro.jpg","File:Carnavales Oruro dia II (68).JPG","File:El carnaval de Oruro 2.jpg"],
  },
  {
    key: 'oru-mirador', provider: 'altura', city: 'Oruro', cats: ['CU', 'NA'],
    title: 'Teleférico al monumento de la Virgen del Socavón',
    description: 'Subida en teleférico al cerro Santa Bárbara, donde se levanta el monumento a la Virgen del Socavón, una de las estatuas más altas de Sudamérica. Desde el mirador se ve toda la ciudad de Oruro, el altiplano y el lago Uru Uru.',
    includes: 'Guía, pasaje de teleférico ida y vuelta.', excludes: 'Alimentación.',
    minutes: 150, label: '2 h 30 min', price: 90, start: '15:30:00', slots: 16,
    files: ["File:Monumento a la Virgen del Socavón de noche.jpg", "File:Ciudad de Oruro, Bolivia.jpg", "File:Oruro..jpg"],
  },
  {
    key: 'oru-uru-uru', provider: 'altura', city: 'Oruro', cats: ['NA'],
    title: 'Flamencos en el lago Uru Uru',
    description: 'Salida temprano al lago Uru Uru, a las afueras de Oruro, para observar flamencos andinos y otras aves del altiplano en sus orillas. Incluye binoculares y explicación sobre el sistema de lagos Uru Uru y Poopó.',
    includes: 'Transporte, guía, binoculares.', excludes: 'Desayuno.',
    minutes: 210, label: '3 h 30 min', price: 170, start: '07:30:00', slots: 10,
    img: ['Lago Uru Uru', 'Uru Uru flamingos'],
  },

  // ───────────────────────── Uyuni (Altura Viva) ─────────────────────────
  {
    key: 'uyu-atardecer', provider: 'altura', city: 'Uyuni', cats: ['NA'],
    title: 'Atardecer en el Salar de Uyuni',
    description: 'Tarde en el salar de sal más grande del mundo: fotos de perspectiva, los montículos de sal de Colchani y el atardecer sobre la llanura blanca. En temporada de lluvias el salar se vuelve un espejo que refleja el cielo.',
    includes: 'Transporte 4x4, guía, refrigerio al atardecer.', excludes: 'Almuerzo, botas de goma (en época de lluvias).',
    minutes: 360, label: 'Tarde completa', price: 480, start: '14:30:00', slots: 12,
    files: ['File:Watching Sunset Salar de Uyuni Bolivia Luca Galuzzi 2006.jpg', 'File:Reflection on the Salar de Uyuni, bolivia.jpg', 'File:Piles of Salt Salar de Uyuni Bolivia Luca Galuzzi 2006 a.jpg'],
  },
  {
    key: 'uyu-incahuasi', provider: 'altura', city: 'Uyuni', cats: ['NA', 'AV'],
    title: 'Salar de Uyuni e Isla Incahuasi: día completo',
    description: 'Cruce del salar en 4x4 hasta la Isla Incahuasi, un islote cubierto de cactus gigantes en medio de la sal. Paramos en el antiguo hotel de sal, el monumento del Dakar y los ojos de agua, con almuerzo sobre el salar.',
    includes: 'Transporte 4x4, guía, almuerzo.', excludes: 'Entrada a la Isla Incahuasi (se paga en el lugar).',
    minutes: 600, label: 'Día completo', price: 700, start: '10:00:00', slots: 12,
    img: ['Isla Incahuasi', 'Incahuasi cactus Uyuni'],
  },
  {
    key: 'uyu-trenes', provider: 'altura', city: 'Uyuni', cats: ['HI', 'CU'],
    title: 'Cementerio de Trenes y Colchani',
    description: 'Visita al cementerio de locomotoras de vapor abandonadas a las afueras de Uyuni, testimonio del auge ferroviario y minero de fines del siglo XIX, y al pueblo de Colchani, donde se extrae y procesa la sal del salar de forma artesanal.',
    includes: 'Transporte, guía.', excludes: 'Compras de artesanías.',
    minutes: 180, label: '3 horas', price: 140, start: '09:30:00', slots: 16,
    img: ['Train cemetery Uyuni', 'Colchani salt'],
  },
  {
    key: 'uyu-estrellas', provider: 'altura', city: 'Uyuni', cats: ['NA', 'RB'],
    title: 'Noche de estrellas en el Salar',
    description: 'Salida nocturna al salar para mirar el cielo del altiplano lejos de las luces: Vía Láctea, constelaciones del hemisferio sur y, en época de lluvias, el reflejo de las estrellas en el agua. Con bebida caliente y ropa de abrigo extra.',
    includes: 'Transporte 4x4, guía, bebida caliente, mantas.', excludes: 'Cena.',
    minutes: 180, label: '3 horas', price: 380, start: '19:30:00', slots: 10,
    img: ['Salar de Uyuni night', 'Salar de Uyuni stars'],
  },
  {
    key: 'uyu-pulacayo', provider: 'altura', city: 'Uyuni', cats: ['HI'],
    title: 'Pulacayo: el pueblo minero de la plata',
    description: 'Excursión a Pulacayo, antiguo centro minero de plata a unos 20 km de Uyuni. Recorremos el pueblo, sus instalaciones mineras y los vagones históricos del primer ferrocarril de Bolivia.',
    includes: 'Transporte, guía.', excludes: 'Alimentación.',
    minutes: 240, label: 'Medio día', price: 200, start: '09:00:00', slots: 12,
    img: ['Pulacayo'],
  },
  {
    key: 'uyu-bici', provider: 'altura', city: 'Uyuni', cats: ['AV'],
    title: 'Pedaleando sobre la sal',
    description: 'Recorrido en bicicleta por la costra de sal del salar, lejos de las rutas de los vehículos. Un vehículo de apoyo acompaña todo el trayecto y lleva agua y refrigerio.',
    includes: 'Bicicleta, casco, guía, vehículo de apoyo, refrigerio.', excludes: 'Protector solar y lentes de sol.',
    minutes: 300, label: '5 horas', price: 420, start: '09:00:00', slots: 8,
    img: ['Salar de Uyuni bicycle', 'Salar de Uyuni'],
  },

  // ───────────────────────── Copacabana (Lago y Yunga) ─────────────────────────
  {
    key: 'cop-isla-sol', provider: 'lagoyungas', city: 'Copacabana', cats: ['HI', 'NA'],
    title: 'Isla del Sol: caminata sagrada desde Copacabana',
    description: 'Navegación desde Copacabana hasta la Isla del Sol, lugar de origen de los incas según la tradición andina. Caminamos entre terrazas agrícolas prehispánicas hasta la escalera y la fuente de Yumani, con vista al lago Titicaca y a la Cordillera Real.',
    includes: 'Bote ida y vuelta, guía, almuerzo en la isla.', excludes: 'Tasas comunitarias de ingreso (se pagan en la isla).',
    minutes: 540, label: 'Día completo', price: 350, start: '08:00:00', slots: 16,
    img: ['Isla del Sol Bolivia', 'Isla del Sol Titicaca'],
  },
  {
    key: 'cop-calvario', provider: 'lagoyungas', city: 'Copacabana', cats: ['CU', 'HI'],
    title: 'Basílica de Copacabana y atardecer en el Cerro Calvario',
    description: 'Visita a la Basílica de Nuestra Señora de Copacabana, uno de los santuarios más importantes de Bolivia, y subida al Cerro Calvario por el camino de las estaciones del Vía Crucis para ver el atardecer sobre el lago Titicaca.',
    includes: INC_GUIDE, excludes: 'Ofrendas y compras.',
    minutes: 180, label: '3 horas', price: 90, start: '15:30:00', slots: 20,
    img: ['Basílica de Copacabana Bolivia', 'Copacabana Bolivia Cerro Calvario'],
  },
  {
    key: 'cop-kayak', provider: 'lagoyungas', city: 'Copacabana', cats: ['AV', 'NA'],
    title: 'Kayak en la bahía de Copacabana',
    description: 'Paseo en kayak por la bahía de Copacabana sobre las aguas del lago navegable más alto del mundo. Salida por la mañana, cuando el lago suele estar más calmo, con instrucción previa y guía en el agua.',
    includes: 'Kayak, chaleco salvavidas, guía.', excludes: 'Ropa de cambio.',
    minutes: 150, label: '2 h 30 min', price: 160, start: '09:30:00', slots: 8,
    img: ['Copacabana Bolivia lake Titicaca'],
  },

  // ───────────────────────── Coroico (Lago y Yunga) ─────────────────────────
  {
    key: 'cor-uchumachi', provider: 'lagoyungas', city: 'Coroico', cats: ['NA', 'AV'],
    title: 'Cerro Uchumachi: sendero con vista a los Yungas',
    description: 'Ascenso al cerro Uchumachi, que domina el pueblo de Coroico, por un sendero de bosque húmedo con vistas a los valles de los Yungas y a los nevados de la Cordillera Real en días claros.',
    includes: 'Guía, refrigerio.', excludes: 'Repelente de insectos.',
    minutes: 300, label: '5 horas', price: 150, start: '08:00:00', slots: 10,
    img: ['Coroico', 'Coroico Yungas Bolivia'],
  },
  {
    key: 'cor-tocana', provider: 'lagoyungas', city: 'Coroico', cats: ['CU'],
    title: 'Tocaña: comunidad afroboliviana y la saya',
    description: 'Visita de turismo comunitario a Tocaña, comunidad afroboliviana de los Yungas. Conversamos con la comunidad sobre su historia, sus cultivos de coca, café y cítricos, y compartimos una muestra de saya, la música y danza tradicional afroboliviana.',
    includes: 'Transporte, guía, aporte a la comunidad, almuerzo.', excludes: 'Compras.',
    minutes: 240, label: 'Medio día', price: 190, start: '10:00:00', slots: 12,
    files: ["File:Saya Afroboliviana en movimiento.jpg","File:Saya Afroboliviana 08 2025.jpg","File:BAILARINA DE LA SAYA AFROBOLIVIANA.jpg"],
  },
  {
    key: 'cor-cafe', provider: 'lagoyungas', city: 'Coroico', cats: ['GA', 'NA'],
    title: 'Ruta del café de los Yungas',
    description: 'Recorrido por una finca cafetalera de los alrededores de Coroico: cosecha, despulpado, secado y tostado del café de altura de los Yungas, con cata guiada al final.',
    includes: 'Transporte, guía, cata de café.', excludes: 'Compra de café.',
    minutes: 210, label: '3 h 30 min', price: 200, start: '09:00:00', slots: 10,
    files: ["File:Plantacion de cafe.jpg","File:Sultana de los Yungas, cáscara del grano de café.jpg","File:Plantines de café.jpg"],
  },

  // ───────────────────────── Potosí (Quebrada Roja) ─────────────────────────
  {
    key: 'pot-moneda', provider: 'surandino', city: 'Potosí', cats: ['HI', 'CU'],
    title: 'Casa Nacional de Moneda',
    description: 'Visita guiada a la Casa Nacional de Moneda, construida en el siglo XVIII para acuñar la plata del Cerro Rico. Hoy es uno de los museos más completos de Bolivia: maquinaria de acuñación, pintura colonial y la historia de la ciudad que fue Patrimonio de la Humanidad.',
    includes: `${INC_GUIDE} Entrada al museo.`, excludes: 'Permiso de fotografía.',
    minutes: 180, label: '3 horas', price: 120, start: '09:00:00', slots: 20,
    weekdays: [2, 3, 4, 5, 6],
    img: ['Casa Nacional de Moneda Potosí'],
  },
  {
    key: 'pot-cerro-rico', provider: 'surandino', city: 'Potosí', cats: ['HI', 'AV'],
    title: 'Cerro Rico: visita a una mina cooperativa',
    description: 'Ingreso con guía a una mina en actividad del Cerro Rico, explotado desde 1545. Pasamos por el mercado de los mineros y recorremos galerías donde trabajan cooperativas. Visita exigente: galerías estrechas, polvo y altura; no recomendada para personas con claustrofobia o problemas respiratorios.',
    includes: 'Guía ex minero, equipo de protección (casco, lámpara, botas, overol), transporte.', excludes: 'Obsequios para los mineros.',
    minutes: 240, label: 'Medio día', price: 250, start: '08:30:00', slots: 8,
    img: ['Cerro Rico Potosí'],
  },
  {
    key: 'pot-tarapaya', provider: 'surandino', city: 'Potosí', cats: ['RB', 'NA'],
    title: 'Ojo del Inca y aguas termales de Tarapaya',
    description: 'Excursión a la laguna volcánica del Ojo del Inca, de aguas tibias y forma casi circular, y a los baños termales de Tarapaya, a unos 25 km de Potosí.',
    includes: 'Transporte, guía, entradas.', excludes: 'Traje de baño y toalla.',
    minutes: 240, label: 'Medio día', price: 150, start: '10:00:00', slots: 12,
    img: ['Ojo del Inca Tarapaya', 'Tarapaya Potosí'],
  },
  {
    key: 'pot-colonial', provider: 'surandino', city: 'Potosí', cats: ['HI'],
    title: 'Potosí colonial: iglesias, torres y miradores',
    description: 'Caminata por la Villa Imperial: la portada barroca mestiza de San Lorenzo de Carangas, la Catedral, la torre de la Compañía de Jesús y el convento de San Francisco, con subida a un mirador sobre los techos de la ciudad y el Cerro Rico.',
    includes: INC_GUIDE, excludes: 'Entradas a torres y conventos (opcionales).',
    minutes: 180, label: '3 horas', price: 110, start: '15:00:00', slots: 16,
    img: ['Potosí Bolivia iglesia San Lorenzo', 'Torre de la Compañía Potosí'],
  },

  // ───────────────────────── Tupiza (Quebrada Roja) ─────────────────────────
  {
    key: 'tup-palala', provider: 'surandino', city: 'Tupiza', cats: ['NA', 'AV'],
    title: 'Quebrada de Palala y Cañón del Inca',
    description: 'Recorrido por los paisajes de roca roja que rodean Tupiza: la Quebrada de Palala, con sus agujas de arenisca, y la caminata dentro del estrecho Cañón del Inca.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Almuerzo.',
    minutes: 300, label: '5 horas', price: 220, start: '08:30:00', slots: 12,
    img: ['Tupiza Quebrada de Palala', 'Tupiza canyon'],
  },
  {
    key: 'tup-cabalgata', provider: 'surandino', city: 'Tupiza', cats: ['AV', 'NA'],
    title: 'Cabalgata por el Valle de los Machos',
    description: 'Cabalgata entre formaciones rocosas y quebradas de colores del Valle de los Machos, uno de los paisajes clásicos de Tupiza. Caballos mansos y guía; apto para principiantes.',
    includes: 'Caballo, guía, casco.', excludes: 'Almuerzo.',
    minutes: 240, label: 'Medio día', price: 280, start: '09:00:00', slots: 8,
    files: ["File:Cordillera de Chichas en Tupiza, Sud Chichas, Bolivia.jpg","File:224.Tupiza (13).JPG","File:Tupiza desde el cerro Corazon de Jesus.jpg"],
  },
  {
    key: 'tup-duende', provider: 'surandino', city: 'Tupiza', cats: ['NA'],
    title: 'Cañón del Duende al atardecer',
    description: 'Caminata corta al Cañón del Duende, un pasillo angosto de paredes rojizas a pocos minutos de Tupiza, para terminar en un mirador con la luz del atardecer.',
    includes: 'Transporte, guía.', excludes: 'Alimentación.',
    minutes: 180, label: '3 horas', price: 150, start: '15:30:00', slots: 12,
    img: ['Cañón del Duende Tupiza', 'Tupiza landscape'],
  },

  // ───────────────────────── Cochabamba y alrededores (Llajta Verde) ─────────────────────────
  {
    key: 'cbba-cristo', provider: 'llajta', city: 'Cochabamba', cats: ['CU'],
    title: 'Cristo de la Concordia y el cerro San Pedro',
    description: 'Subida en teleférico o a pie al cerro San Pedro, donde se levanta el Cristo de la Concordia, una de las estatuas de Cristo más altas del mundo. Desde el mirador se ve todo el valle de Cochabamba.',
    includes: 'Guía, pasaje de teleférico.', excludes: 'Ingreso al interior de la estatua (cuando está habilitado).',
    minutes: 180, label: '3 horas', price: 90, start: '16:00:00', slots: 20,
    weekdays: [2, 3, 4, 5, 6, 0],
    img: ['Cristo de la Concordia'],
  },
  {
    key: 'cbba-portales', provider: 'llajta', city: 'Cochabamba', cats: ['HI'],
    title: 'Palacio Portales y la historia de Patiño',
    description: 'Visita al Palacio Portales, la residencia de estilo francés que mandó construir el empresario minero Simón I. Patiño a inicios del siglo XX, con sus salones, jardines y la historia del “rey del estaño”.',
    includes: `${INC_GUIDE} Entrada al palacio.`, excludes: 'Transporte.',
    minutes: 150, label: '2 h 30 min', price: 100, start: '10:00:00', slots: 16,
    weekdays: [2, 3, 4, 5, 6],
    img: ['Palacio Portales Cochabamba'],
  },
  {
    key: 'cbba-cancha', provider: 'llajta', city: 'Cochabamba', cats: ['CU', 'GA'],
    title: 'La Cancha: el gran mercado de Cochabamba',
    description: 'Inmersión en La Cancha, uno de los mercados al aire libre más grandes de Sudamérica: frutas del trópico, especias, tejidos, hierbas medicinales y comedores populares, con degustaciones en el camino.',
    includes: 'Guía, degustaciones.', excludes: 'Compras.',
    minutes: 180, label: '3 horas', price: 130, start: '09:30:00', slots: 10,
    img: ['La Cancha Cochabamba'],
  },
  {
    key: 'cbba-sabores', provider: 'llajta', city: 'Cochabamba', cats: ['GA'],
    title: 'Ruta gastronómica cochabambina',
    description: 'Cochabamba es la capital gastronómica de Bolivia. En este almuerzo recorrido probamos silpancho, pique macho, chicharrón y api, y conocemos la tradición de la chicha de maíz en una picantería del valle.',
    includes: 'Guía, degustaciones y almuerzo, transporte entre paradas.', excludes: 'Bebidas adicionales.',
    minutes: 210, label: '3 h 30 min', price: 240, start: '12:00:00', slots: 12,
    img: ['Silpancho', 'Pique macho'],
  },
  {
    key: 'cbba-incallajta', provider: 'llajta', city: 'Cochabamba', cats: ['HI'],
    title: 'Incallajta: la fortaleza inca del oriente',
    description: 'Salida de día completo al complejo arqueológico de Incallajta, en Pocona, uno de los sitios incas más grandes de Bolivia. Recorremos la gran kallanka, las murallas y el sistema de terrazas en el límite oriental del Tawantinsuyu.',
    includes: 'Transporte, guía, entrada, almuerzo campestre.', excludes: 'Propinas.',
    minutes: 600, label: 'Día completo', price: 380, start: '07:30:00', slots: 12,
    img: ['Incallajta'],
  },
  {
    key: 'cbba-alalay', provider: 'llajta', city: 'Cochabamba', cats: ['NA'],
    title: 'Aves de la laguna Alalay',
    description: 'Caminata temprano por la orilla de la laguna Alalay, humedal urbano de Cochabamba, para observar patos, garzas, gallaretas y otras aves acuáticas con un guía especializado.',
    includes: 'Guía, binoculares.', excludes: 'Transporte.',
    minutes: 150, label: '2 h 30 min', price: 80, start: '07:00:00', slots: 12,
    img: ['Laguna Alalay'],
  },
  {
    key: 'qui-urkupina', provider: 'llajta', city: 'Quillacollo', cats: ['CU', 'HI'],
    title: 'Quillacollo y el santuario de Urkupiña',
    description: 'Visita a Quillacollo, en el valle bajo, y al santuario de la Virgen de Urkupiña, centro de una de las festividades religiosas más concurridas de Bolivia. Subimos al Calvario, donde los devotos piden favores rompiendo piedras.',
    includes: 'Transporte desde Cochabamba, guía.', excludes: 'Ofrendas.',
    minutes: 180, label: '3 horas', price: 110, start: '10:00:00', slots: 16,
    img: ['Urkupiña Quillacollo', 'Quillacollo'],
  },
  {
    key: 'sip-inkarakay', provider: 'llajta', city: 'Sipe Sipe', cats: ['HI', 'AV'],
    title: 'Inkarakay: ruinas incas sobre el valle',
    description: 'Caminata de subida desde Sipe Sipe hasta Inkarakay, un asentamiento inca en lo alto del cerro con recintos de piedra y vista a todo el valle de Cochabamba.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Almuerzo.',
    minutes: 300, label: '5 horas', price: 180, start: '08:30:00', slots: 12,
    files: ["File:Ruinas de Inka Raqay.jpg","File:Salida del sol - inka rakay.JPG","File:Monumento arqueológico de Inca Rakay.jpg"],
  },
  {
    key: 'tiq-tunari', provider: 'llajta', city: 'Tiquipaya', cats: ['NA', 'AV'],
    title: 'Senderos del Parque Nacional Tunari desde Tiquipaya',
    description: 'Trekking desde Tiquipaya hacia las quebradas del Parque Nacional Tunari, con bosques de queñua, arroyos y vistas del valle desde la cordillera que protege a Cochabamba.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Calzado de trekking.',
    minutes: 360, label: '6 horas', price: 170, start: '08:00:00', slots: 10,
    img: ['Parque Nacional Tunari', 'Tunari Cochabamba'],
  },

  // ───────────────────────── Villa Tunari (Llajta Verde) ─────────────────────────
  {
    key: 'vt-machia', provider: 'llajta', city: 'Villa Tunari', cats: ['NA'],
    title: 'Parque Machía y senderos del trópico',
    description: 'Caminata por los senderos del Parque Machía, junto a Villa Tunari, entre bosque tropical húmedo, miradores al río y la labor de rescate de fauna silvestre que se desarrolla en la zona.',
    includes: 'Guía, entrada.', excludes: 'Repelente, alimentación.',
    minutes: 240, label: 'Medio día', price: 130, start: '09:00:00', slots: 12,
    img: ['Parque Machía Villa Tunari', 'Villa Tunari'],
  },
  {
    key: 'vt-rafting', provider: 'llajta', city: 'Villa Tunari', cats: ['AV'],
    title: 'Rafting en el río Espíritu Santo',
    description: 'Descenso en balsa por los rápidos del río Espíritu Santo, en el trópico de Cochabamba, con instructores certificados. Incluye charla de seguridad y práctica en aguas calmas antes de los tramos movidos.',
    includes: 'Balsa, casco, chaleco, instructor, transporte al punto de embarque.', excludes: 'Ropa de cambio.',
    minutes: 240, label: 'Medio día', price: 320, start: '10:00:00', slots: 8,
    img: ['Río Espíritu Santo Villa Tunari', 'Chapare river'],
  },
  {
    key: 'vt-repechon', provider: 'llajta', city: 'Villa Tunari', cats: ['NA', 'AV'],
    title: 'Cavernas del Repechón y los guácharos',
    description: 'Visita al Parque Nacional Carrasco para conocer las Cavernas del Repechón, refugio de colonias de guácharos, aves nocturnas que se orientan por ecolocación. Se cruza el río en un sistema de canastilla colgante.',
    includes: 'Transporte, guía, entrada al área protegida.', excludes: 'Linterna frontal.',
    minutes: 240, label: 'Medio día', price: 180, start: '14:00:00', slots: 10,
    img: ['Parque Nacional Carrasco Bolivia', 'Steatornis caripensis'],
  },

  // ───────────────────────── Torotoro (Llajta Verde) ─────────────────────────
  {
    key: 'tor-huellas', provider: 'llajta', city: 'Torotoro', cats: ['NA', 'HI'],
    title: 'Huellas de dinosaurio y el cañón de Torotoro',
    description: 'Recorrido por el Parque Nacional Torotoro, que guarda miles de huellas de dinosaurios del Cretácico. Seguimos rastros en el lecho de roca y bajamos al cañón para llegar a la cascada de El Vergel por una escalinata de unos 900 escalones.',
    includes: 'Guía local autorizado, entrada al parque.', excludes: 'Almuerzo.',
    minutes: 300, label: '5 horas', price: 200, start: '08:30:00', slots: 12,
    img: ['Torotoro dinosaur footprints', 'Torotoro canyon'],
  },
  {
    key: 'tor-umajalanta', provider: 'llajta', city: 'Torotoro', cats: ['AV'],
    title: 'Caverna de Umajalanta',
    description: 'Espeleología guiada en Umajalanta, una de las cavernas más largas de Bolivia: pasadizos, estalactitas y un lago subterráneo habitado por peces ciegos. Hay tramos donde es necesario gatear.',
    includes: 'Guía, casco con linterna, entrada al parque.', excludes: 'Ropa que se pueda ensuciar.',
    minutes: 300, label: '5 horas', price: 220, start: '09:00:00', slots: 10,
    img: ['Umajalanta', 'Torotoro cave'],
  },
  {
    key: 'tor-itas', provider: 'llajta', city: 'Torotoro', cats: ['NA', 'HI'],
    title: 'Ciudad de Itas y pinturas rupestres',
    description: 'Excursión a la Ciudad de Itas, un laberinto de formaciones de roca sedimentaria con galerías naturales a una hora del pueblo de Torotoro, y a sitios con pinturas rupestres.',
    includes: 'Transporte, guía, entrada al parque, refrigerio.', excludes: 'Almuerzo.',
    minutes: 360, label: '6 horas', price: 240, start: '08:00:00', slots: 10,
    img: ['Ciudad de Itas Torotoro', 'Torotoro National Park'],
  },

  // ───────────────────────── Sucre (Charcas) ─────────────────────────
  {
    key: 'suc-ciudad-blanca', provider: 'charcas', city: 'Sucre', cats: ['HI', 'CU'],
    title: 'Sucre, la Ciudad Blanca a pie',
    description: 'Caminata por el centro histórico de Sucre, Patrimonio de la Humanidad: la Plaza 25 de Mayo, la Catedral Metropolitana, el convento de San Felipe Neri y sus terrazas, y las calles de casonas blancas que dieron nombre a la ciudad.',
    includes: INC_GUIDE, excludes: 'Entradas a conventos (opcionales).',
    minutes: 180, label: '3 horas', price: 120, start: '09:30:00', slots: 20,
    img: ['Sucre Bolivia Plaza 25 de Mayo', 'San Felipe Neri Sucre'],
  },
  {
    key: 'suc-libertad', provider: 'charcas', city: 'Sucre', cats: ['HI'],
    title: 'Casa de la Libertad: donde nació Bolivia',
    description: 'Visita a la Casa de la Libertad, donde en 1825 se firmó el Acta de Independencia de Bolivia. Sus salas guardan el acta original, retratos y objetos de la guerra de independencia.',
    includes: `${INC_GUIDE} Entrada al museo.`, excludes: 'Transporte.',
    minutes: 120, label: '2 horas', price: 90, start: '10:00:00', slots: 20,
    weekdays: [2, 3, 4, 5, 6, 0],
    img: ['Casa de la Libertad Sucre'],
  },
  {
    key: 'suc-cal-orcko', provider: 'charcas', city: 'Sucre', cats: ['NA', 'HI'],
    title: 'Parque Cretácico y la pared de Cal Orck\'o',
    description: 'Visita al Parque Cretácico, frente a la pared de Cal Orck\'o, una ladera casi vertical con miles de huellas de dinosaurios. Réplicas a escala real, museo y mirador con vista a los rastros.',
    includes: 'Transporte, guía, entrada al parque.', excludes: 'Alimentación.',
    minutes: 180, label: '3 horas', price: 150, start: '10:00:00', slots: 20,
    img: ["Cal Orck'o", 'Parque Cretácico Sucre'],
  },
  {
    key: 'suc-recoleta', provider: 'charcas', city: 'Sucre', cats: ['CU'],
    title: 'Mirador de La Recoleta al atardecer',
    description: 'Subida al barrio de La Recoleta, con su plaza de arcos, el convento franciscano y el mirador desde donde se ve toda la ciudad de techos de teja. Terminamos con el atardecer sobre Sucre.',
    includes: INC_GUIDE, excludes: 'Entrada al museo de La Recoleta (opcional).',
    minutes: 150, label: '2 h 30 min', price: 80, start: '16:30:00', slots: 20,
    img: ['La Recoleta Sucre', 'Mirador Recoleta Sucre'],
  },
  {
    key: 'suc-glorieta', provider: 'charcas', city: 'Sucre', cats: ['HI'],
    title: 'Castillo de la Glorieta',
    description: 'Visita al Castillo de la Glorieta, residencia ecléctica de fines del siglo XIX construida por los príncipes de La Glorieta, Francisco Argandoña y Clotilde Urioste, a las afueras de Sucre.',
    includes: 'Transporte, guía, entrada.', excludes: 'Alimentación.',
    minutes: 180, label: '3 horas', price: 110, start: '14:00:00', slots: 16,
    img: ['Castillo de la Glorieta'],
  },
  {
    key: 'suc-tarabuco', provider: 'charcas', city: 'Sucre', cats: ['CU'],
    title: 'Mercado dominical de Tarabuco',
    description: 'Salida de domingo al mercado de Tarabuco, a unos 65 km de Sucre, donde comunidades yampara venden y compran productos del campo y tejidos de diseño propio. Visitamos también el museo de textiles de la zona.',
    includes: 'Transporte, guía.', excludes: 'Almuerzo, compras.',
    minutes: 420, label: '7 horas', price: 220, start: '08:00:00', slots: 14,
    weekdays: [0],
    img: ['Tarabuco'],
  },
  {
    key: 'suc-maragua', provider: 'charcas', city: 'Sucre', cats: ['NA', 'CU'],
    title: 'Cráter de Maragua y comunidades jalq\'a',
    description: 'Excursión a la cordillera de los Frailes: el sinclinal de Maragua, conocido como cráter por su forma, con colinas de franjas de colores, huellas de dinosaurio en Niñu Mayu y la tradición textil de las comunidades jalq\'a.',
    includes: 'Transporte, guía, almuerzo comunitario.', excludes: 'Compras de tejidos.',
    minutes: 600, label: 'Día completo', price: 380, start: '07:30:00', slots: 10,
    files: ["File:084 - sunrise in Maragua crater.jpg","File:Maragua crater's local house (14277812952).jpg","File:Marágua - Sucre I.jpg"],
  },
  {
    key: 'suc-chataquila', provider: 'charcas', city: 'Sucre', cats: ['NA', 'AV'],
    title: 'Chataquila y el camino prehispánico',
    description: 'Trekking en la cordillera de los Frailes: partimos de la capilla de Chataquila, en lo alto de la serranía, y bajamos por un antiguo camino empedrado prehispánico entre quebradas y comunidades campesinas hasta el valle.',
    includes: 'Transporte ida y vuelta, guía, refrigerio.', excludes: 'Calzado de trekking.',
    minutes: 360, label: '6 horas', price: 200, start: '08:00:00', slots: 12,
    files: ["File:045 - Chataquila.jpg", "File:Frailes 3345.jpg", "File:Frailes 3342.jpg"],
  },
  {
    key: 'suc-sabores', provider: 'charcas', city: 'Sucre', cats: ['GA'],
    title: 'Chocolate, chorizos y sabores de Sucre',
    description: 'Sucre es conocida por su chocolate y sus chorizos chuquisaqueños. Recorremos el Mercado Central y talleres de la ciudad con degustación de chocolates, salteñas y jugos del mercado.',
    includes: 'Guía, degustaciones.', excludes: 'Compras.',
    minutes: 150, label: '2 h 30 min', price: 180, start: '16:00:00', slots: 10,
    img: ['Mercado Central Sucre', 'Chorizo chuquisaqueño'],
  },

  // ───────────────────────── Tarija, Bermejo y Villamontes (Cepa Chapaca) ─────────────────────────
  {
    key: 'tja-vino', provider: 'chapaca', city: 'Tarija', cats: ['GA', 'CU'],
    title: 'Ruta del vino de altura: Valle de la Concepción',
    description: 'Recorrido por bodegas del Valle de la Concepción, corazón de los viñedos tarijeños, cultivados a más de 1.700 m de altura. Visitamos viñedos, salas de elaboración y hacemos catas guiadas de vinos de la región.',
    includes: 'Transporte, guía, catas en bodegas, almuerzo.', excludes: 'Compra de vinos.',
    minutes: 360, label: '6 horas', price: 380, start: '09:30:00', slots: 14,
    img: ['Valle de la Concepción Tarija', 'Viñedos Tarija'],
  },
  {
    key: 'tja-singani', provider: 'chapaca', city: 'Tarija', cats: ['GA'],
    title: 'Singani: de la uva moscatel a la copa',
    description: 'Visita a destilerías de singani, el aguardiente de uva moscatel de Alejandría con denominación de origen boliviana. Vemos el proceso de destilación y hacemos una cata comparada. Sólo para mayores de 18 años.',
    includes: 'Transporte, guía, cata.', excludes: 'Compras.',
    minutes: 240, label: 'Medio día', price: 300, start: '15:00:00', slots: 12,
    files: ["File:Valle de Santa Ana en Tarija - Cercado, Bolivia.jpg","File:Viñedos bolivianos - Valle de Santa Ana - Cercado, Bolivia.jpg"],
  },
  {
    key: 'tja-coimata', provider: 'chapaca', city: 'Tarija', cats: ['NA', 'RB'],
    title: 'Coimata: cascadas y pozas naturales',
    description: 'Día de río en Coimata, a unos 15 km de Tarija, con senderos entre cascadas y pozas de agua cristalina en la reserva de la Cordillera de Sama.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Traje de baño.',
    minutes: 300, label: '5 horas', price: 140, start: '09:30:00', slots: 14,
    img: ['Coimata Tarija'],
  },
  {
    key: 'tja-ciudad', provider: 'chapaca', city: 'Tarija', cats: ['HI', 'CU'],
    title: 'Tarija a pie: plaza Luis de Fuentes y Casa Dorada',
    description: 'Caminata por el centro de Tarija, la ciudad de las flores: plaza Luis de Fuentes, la Catedral, la Casa Dorada de estilo neoclásico y la iglesia de San Francisco, con historias de la cultura chapaca.',
    includes: INC_GUIDE, excludes: 'Transporte.',
    minutes: 150, label: '2 h 30 min', price: 90, start: '10:00:00', slots: 20,
    img: ['Casa Dorada Tarija', 'Plaza Luis de Fuentes Tarija'],
  },
  {
    key: 'tja-paleontologico', provider: 'chapaca', city: 'Tarija', cats: ['HI'],
    title: 'Museo Paleontológico y megafauna de Tarija',
    description: 'Visita al Museo Nacional Paleontológico y Arqueológico de Tarija, con fósiles de megafauna del Pleistoceno hallados en el valle, como mastodontes y gliptodontes, y piezas arqueológicas de la región.',
    includes: `${INC_GUIDE} Entrada al museo.`, excludes: 'Transporte.',
    minutes: 120, label: '2 horas', price: 70, start: '15:00:00', slots: 20,
    weekdays: [1, 2, 3, 4, 5, 6],
    img: ['Museo Paleontológico Tarija', 'Tarija museo'],
  },
  {
    key: 'tja-tajzara', provider: 'chapaca', city: 'Tarija', cats: ['NA'],
    title: 'Lagunas de Tajzara en la Reserva de Sama',
    description: 'Excursión a la zona altoandina de la Reserva Biológica Cordillera de Sama para visitar las lagunas de Tajzara, humedal Ramsar con flamencos y dunas de arena a unos 3.700 m de altura.',
    includes: 'Transporte 4x4, guía, almuerzo.', excludes: 'Ropa de abrigo.',
    minutes: 600, label: 'Día completo', price: 420, start: '07:00:00', slots: 10,
    img: ['Tajzara', 'Cordillera de Sama'],
  },
  {
    key: 'tja-san-jacinto', provider: 'chapaca', city: 'Tarija', cats: ['AV', 'RB'],
    title: 'Represa de San Jacinto en bicicleta',
    description: 'Paseo en bicicleta por caminos rurales hasta el lago de la represa de San Jacinto, a pocos kilómetros de Tarija, con parada para paseo en bote y almuerzo de pescado.',
    includes: 'Bicicleta, casco, guía, paseo en bote.', excludes: 'Almuerzo.',
    minutes: 240, label: 'Medio día', price: 160, start: '09:00:00', slots: 10,
    img: ['San Jacinto Tarija', 'Represa San Jacinto'],
  },
  {
    key: 'tja-sabores', provider: 'chapaca', city: 'Tarija', cats: ['GA'],
    title: 'Sabores chapacos: saice, cangrejitos y rosquetes',
    description: 'Almuerzo recorrido por la cocina tarijeña: saice, ranga, cangrejitos de pasta frita y rosquetes, acompañados de historias de la cultura chapaca en el Mercado Central y una casa de comidas tradicional.',
    includes: 'Guía, degustaciones y almuerzo.', excludes: 'Bebidas alcohólicas.',
    minutes: 180, label: '3 horas', price: 190, start: '12:00:00', slots: 12,
    img: ['Saice', 'Tarija comida'],
  },
  {
    key: 'ber-tariquia', provider: 'chapaca', city: 'Bermejo', cats: ['NA', 'AV'],
    title: 'Reserva de Tariquía: trekking en bosque nublado',
    description: 'Trekking de día completo en la Reserva Nacional de Flora y Fauna Tariquía, bosque tucumano-boliviano y yungas que protegen las nacientes de agua del sur de Tarija. Observación de aves, ríos de agua cristalina y comunidades campesinas.',
    includes: 'Transporte desde Bermejo, guía, almuerzo.', excludes: 'Repelente.',
    minutes: 540, label: 'Día completo', price: 420, start: '07:00:00', slots: 10,
    files: ["File:Tariquia..jpg","File:RESERVA NACIONAL DE TARIQUIADSC07283.jpg"],
  },
  {
    key: 'vm-pilcomayo', provider: 'chapaca', city: 'Villamontes', cats: ['NA', 'HI'],
    title: 'Cañón del Pilcomayo y la historia del Chaco',
    description: 'Excursión al cañón del río Pilcomayo, a unos 10 km de Villamontes, con formaciones rocosas y pescadores del río, y visita a sitios de memoria de la Guerra del Chaco en la ciudad.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Almuerzo.',
    minutes: 300, label: '5 horas', price: 200, start: '08:00:00', slots: 12,
    img: ['Pilcomayo Villamontes', 'Villa Montes Bolivia'],
  },
  {
    key: 'vm-aguarague', provider: 'chapaca', city: 'Villamontes', cats: ['NA'],
    title: 'Parque Aguaragüe: senderos del Chaco',
    description: 'Caminata en el Parque Nacional y Área de Manejo Integrado Serranía del Aguaragüe, al oeste de Villamontes, con vegetación chaqueña, vertientes y observación de fauna.',
    includes: 'Transporte, guía, refrigerio.', excludes: 'Repelente.',
    minutes: 300, label: '5 horas', price: 180, start: '08:00:00', slots: 10,
    files: ["File:Serranía del Aguaragüe - Sector de El Angosto.jpg","File:Cascada en el Aguarague.jpg","File:Serranía del Aguaragüe cerca a Boyuibe - Cordillera, Bolivia.jpg"],
  },

  // ───────────────────────── Santa Cruz, Samaipata y Chiquitos (Curichi) ─────────────────────────
  {
    key: 'scz-centro', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['HI', 'CU'],
    title: 'Santa Cruz histórica: plaza 24 de Septiembre y la Catedral',
    description: 'Caminata por el casco viejo de Santa Cruz de la Sierra: la plaza 24 de Septiembre, la Catedral Basílica de San Lorenzo con subida a su campanario, las galerías con columnas de madera y la historia de la ciudad fundada en 1561.',
    includes: INC_GUIDE, excludes: 'Entrada al campanario y museo de la Catedral.',
    minutes: 150, label: '2 h 30 min', price: 90, start: '09:30:00', slots: 20,
    img: ['Catedral de Santa Cruz de la Sierra', 'Plaza 24 de Septiembre Santa Cruz'],
  },
  {
    key: 'scz-botanico', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['NA'],
    title: 'Jardín Botánico de Santa Cruz: senderos y fauna',
    description: 'Caminata por los senderos del Jardín Botánico Municipal de Santa Cruz, un bosque semideciduo dentro de la ciudad donde es posible ver perezosos, monos y aves del oriente.',
    includes: 'Transporte, guía, entrada.', excludes: 'Repelente.',
    minutes: 180, label: '3 horas', price: 90, start: '08:30:00', slots: 15,
    files: ["File:Jardín Botánico Municipal.jpg","File:Jardín Botánico de Santa Cruz.jpg"],
  },
  {
    key: 'scz-lomas-arena', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['AV', 'NA'],
    title: 'Lomas de Arena: dunas en el trópico',
    description: 'Excursión al Parque Regional Lomas de Arena, al sur de la ciudad, donde dunas de arena blanca conviven con lagunas y bosque. Caminata, sandboard en las dunas y observación de aves.',
    includes: 'Transporte, guía, tabla de sandboard, entrada.', excludes: 'Almuerzo.',
    minutes: 300, label: '5 horas', price: 200, start: '08:30:00', slots: 12,
    img: ['Lomas de Arena Santa Cruz'],
  },
  {
    key: 'elt-delicias', provider: 'curichi', city: 'Santiago del Torno', cats: ['NA', 'RB'],
    title: 'Cascada del Jardín de las Delicias',
    description: 'Día de naturaleza en El Torno, a unos 30 km de Santa Cruz, en las estribaciones del Amboró: caminata por un cañón de bosque húmedo hasta la cascada del Jardín de las Delicias, con pozas para bañarse.',
    includes: 'Transporte, guía, entrada, almuerzo.', excludes: 'Traje de baño.',
    minutes: 480, label: 'Día completo', price: 280, start: '08:00:00', slots: 12,
    files: ["File:Cascada del Jardín de las Delicias - El Torno, Bolivia (2025).jpg", "File:Cañón cerca a la cascada del Jardín de las Delicias - El Torno, Bolivia.jpg"],
  },
  {
    key: 'scz-sabores', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['GA'],
    title: 'Sabores cruceños: majadito, cuñapé y zonzo',
    description: 'Recorrido gastronómico por la cocina camba: majadito, locro de gallina, cuñapé y zonzo de yuca, somó y chicha de maní, en mercados y casas de comida tradicionales.',
    includes: 'Guía, degustaciones y almuerzo, transporte entre paradas.', excludes: 'Bebidas alcohólicas.',
    minutes: 180, label: '3 horas', price: 180, start: '11:00:00', slots: 12,
    files: ["File:Majadito de Santa Cruz.jpg","File:Plato de majadito.jpg","File:Majadito o majau.jpg"],
  },
  {
    key: 'scz-los-pozos', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['GA', 'CU'],
    title: 'Mercado Los Pozos y frutas del oriente',
    description: 'Visita al Mercado Los Pozos para conocer las frutas y productos del oriente boliviano: achachairú, pacay, guapurú, cacao, yuca y jugos recién exprimidos, con degustación guiada.',
    includes: 'Guía, degustación.', excludes: 'Compras.',
    minutes: 150, label: '2 h 30 min', price: 110, start: '09:00:00', slots: 10,
    files: ["File:Fruto de Achachairú garcinia humilis.jpg","File:Achachairú .jpg","File:Árbol de Achachairu (Garcinia humilis).jpg"],
  },
  {
    key: 'scz-pirai', provider: 'curichi', city: 'Santa Cruz de la Sierra', cats: ['GA', 'RB'],
    title: 'Tarde en las cabañas del río Piraí',
    description: 'Paseo de fin de tarde a la ribera del río Piraí, tradicional lugar de encuentro de los cruceños, con caminata por la orilla y comida típica en los comedores de las cabañas.',
    includes: 'Transporte, guía, comida típica.', excludes: 'Bebidas adicionales.',
    minutes: 180, label: '3 horas', price: 150, start: '16:00:00', slots: 14,
    weekdays: [5, 6, 0],
    img: ['Río Piraí Santa Cruz'],
  },
  {
    key: 'cot-santuario', provider: 'curichi', city: 'Cotoca', cats: ['CU', 'HI'],
    title: 'Cotoca: santuario y artesanía en cerámica',
    description: 'Visita a Cotoca, a unos 20 km de Santa Cruz, para conocer el santuario de la Virgen de Cotoca, patrona del oriente boliviano, y los talleres de cerámica y los puestos de dulces tradicionales del pueblo.',
    includes: 'Transporte, guía.', excludes: 'Compras.',
    minutes: 180, label: '3 horas', price: 100, start: '09:00:00', slots: 16,
    files: ["File:Santuario de la Virgen de Cotoca.JPG","File:Virgen de Cotoca.JPG"],
  },
  {
    key: 'sam-fuerte', provider: 'curichi', city: 'Samaipata', cats: ['HI'],
    title: 'El Fuerte de Samaipata',
    description: 'Visita al Fuerte de Samaipata, Patrimonio de la Humanidad: una gran roca esculpida con canales, felinos y hornacinas, centro ceremonial de culturas prehispánicas con ocupación inca y luego española.',
    includes: 'Transporte desde Samaipata, guía, entrada al sitio y al museo.', excludes: 'Almuerzo.',
    minutes: 240, label: 'Medio día', price: 180, start: '09:00:00', slots: 16,
    img: ['Fuerte de Samaipata', 'El Fuerte Samaipata'],
  },
  {
    key: 'sam-helechos', provider: 'curichi', city: 'Samaipata', cats: ['NA', 'AV'],
    title: 'Helechos gigantes del Parque Amboró',
    description: 'Trekking en el sector de La Yunga del Parque Nacional Amboró, entre bosque nublado y helechos gigantes arborescentes que superan los 10 metros. Observación de aves y orquídeas.',
    includes: 'Transporte 4x4, guía, entrada al área protegida, almuerzo de campo.', excludes: 'Ropa impermeable.',
    minutes: 540, label: 'Día completo', price: 380, start: '07:30:00', slots: 10,
    img: ['Amboró helechos gigantes', 'Parque Nacional Amboró'],
  },
  {
    key: 'sam-cuevas', provider: 'curichi', city: 'Samaipata', cats: ['NA', 'RB'],
    title: 'Cascadas de Las Cuevas',
    description: 'Paseo a Las Cuevas, cerca de Samaipata, con tres cascadas escalonadas y pozas de arena donde se puede nadar, rodeadas de vegetación de valle.',
    includes: 'Transporte, guía, entrada.', excludes: 'Traje de baño, almuerzo.',
    minutes: 240, label: 'Medio día', price: 150, start: '10:00:00', slots: 14,
    img: ['Las Cuevas Samaipata'],
  },
  {
    key: 'sam-pueblo-vinos', provider: 'curichi', city: 'Samaipata', cats: ['GA', 'CU'],
    title: 'Samaipata: pueblo colonial y vinos de valle',
    description: 'Tarde por las calles coloniales de Samaipata, su plaza y su museo arqueológico, con visita a un viñedo de los valles cruceños y cata de vinos locales al atardecer.',
    includes: 'Guía, transporte al viñedo, cata.', excludes: 'Cena.',
    minutes: 180, label: '3 horas', price: 220, start: '15:00:00', slots: 12,
    img: ['Samaipata town', 'Samaipata Bolivia'],
  },
  {
    key: 'siv-san-miguel', provider: 'curichi', city: 'San Ignacio de Velasco', cats: ['HI', 'CU'],
    title: 'Misiones de Chiquitos: San Miguel y San Rafael',
    description: 'Día en el triángulo misional de Velasco para visitar los templos jesuíticos de San Miguel y San Rafael, parte de las Misiones Jesuíticas de Chiquitos, Patrimonio de la Humanidad. Retablos dorados, pintura mural y talleres donde aún se tallan piezas en madera.',
    includes: 'Transporte desde San Ignacio, guía, almuerzo.', excludes: 'Aportes voluntarios a los templos.',
    minutes: 540, label: 'Día completo', price: 420, start: '08:00:00', slots: 14,
    img: ['San Miguel de Velasco iglesia', 'San Rafael de Velasco'],
  },
  {
    key: 'siv-santa-ana', provider: 'curichi', city: 'San Ignacio de Velasco', cats: ['HI', 'CU'],
    title: 'Templo de San Ignacio y la misión de Santa Ana',
    description: 'Visita al templo de San Ignacio de Velasco, con sus columnas de madera y retablo mayor, y a Santa Ana de Velasco, la misión que mejor conserva su aspecto original y donde se guarda un órgano del siglo XVIII.',
    includes: 'Transporte, guía.', excludes: 'Aportes voluntarios a los templos.',
    minutes: 300, label: '5 horas', price: 220, start: '09:00:00', slots: 16,
    img: ['Santa Ana de Velasco', 'San Ignacio de Velasco iglesia'],
  },
  {
    key: 'siv-guapomo', provider: 'curichi', city: 'San Ignacio de Velasco', cats: ['NA', 'RB'],
    title: 'Atardecer en canoa en la laguna Guapomó',
    description: 'Paseo en canoa por la laguna Guapomó, junto a San Ignacio de Velasco, al caer la tarde, con observación de aves acuáticas y el atardecer chiquitano.',
    includes: 'Canoa, chaleco salvavidas, guía.', excludes: 'Cena.',
    minutes: 180, label: '3 horas', price: 120, start: '16:00:00', slots: 10,
    img: ['Laguna Guapomó', 'San Ignacio de Velasco'],
  },

  // ───────────────────────── Amazonía (Jichi) ─────────────────────────
  {
    key: 'rur-madidi', provider: 'jichi', city: 'Rurrenabaque', cats: ['NA', 'AV'],
    title: 'Madidi: un día en la selva',
    description: 'Navegación por el río Beni y el Tuichi hasta el Parque Nacional Madidi, una de las áreas protegidas con mayor biodiversidad del planeta. Caminata guiada por senderos de selva con árboles gigantes, huellas de fauna y plantas medicinales.',
    includes: 'Bote, guía naturalista, entrada al parque, almuerzo.', excludes: 'Repelente y botas de goma.',
    minutes: 540, label: 'Día completo', price: 480, start: '07:30:00', slots: 10,
    img: ['Madidi National Park', 'Parque Nacional Madidi'],
  },
  {
    key: 'rur-pampas', provider: 'jichi', city: 'Rurrenabaque', cats: ['NA'],
    title: 'Pampas del Yacuma: caimanes, capibaras y aves',
    description: 'Salida a las pampas del río Yacuma, sabanas inundables donde es fácil ver caimanes, capibaras, monos, delfines rosados de río y decenas de especies de aves desde el bote.',
    includes: 'Transporte, bote, guía, entrada al área protegida, almuerzo.', excludes: 'Repelente.',
    minutes: 600, label: 'Día completo', price: 520, start: '07:00:00', slots: 10,
    img: ['Pampas del Yacuma', 'Yacuma river Bolivia'],
  },
  {
    key: 'rur-rio-beni', provider: 'jichi', city: 'Rurrenabaque', cats: ['NA', 'RB'],
    title: 'Río Beni en bote y mirador de Rurrenabaque',
    description: 'Paseo en bote por el río Beni frente a Rurrenabaque y San Buenaventura, y subida al mirador de la cruz para ver el atardecer sobre la selva y el río.',
    includes: 'Bote, guía.', excludes: 'Bebidas.',
    minutes: 180, label: '3 horas', price: 140, start: '15:30:00', slots: 12,
    img: ['Rurrenabaque', 'Beni River Rurrenabaque'],
  },
  {
    key: 'tri-laguna-suarez', provider: 'jichi', city: 'Trinidad', cats: ['NA', 'HI'],
    title: 'Laguna Suárez y la cultura de las lomas',
    description: 'Tarde en la laguna Suárez, a pocos kilómetros de Trinidad, una laguna artificial atribuida a la cultura prehispánica de las lomas de Moxos, con paseo en bote y almuerzo de pescado.',
    includes: 'Transporte, guía, paseo en bote.', excludes: 'Alimentación.',
    minutes: 240, label: 'Medio día', price: 160, start: '14:30:00', slots: 14,
    img: ['Laguna Suárez Trinidad', 'Trinidad Beni'],
  },
  {
    key: 'tri-chuchini', provider: 'jichi', city: 'Trinidad', cats: ['HI', 'NA'],
    title: 'Chuchini: loma prehispánica de Moxos',
    description: 'Excursión a Chuchini, una loma artificial de la cultura hidráulica de Moxos a orillas del río Ibare, con piezas arqueológicas, canales y bosque ribereño con monos y aves.',
    includes: 'Transporte fluvial y terrestre, guía, almuerzo.', excludes: 'Repelente.',
    minutes: 300, label: '5 horas', price: 220, start: '08:30:00', slots: 10,
    img: ['Llanos de Moxos', 'Beni Bolivia river'],
  },
  {
    key: 'rib-cachuela', provider: 'jichi', city: 'Riberalta', cats: ['HI', 'NA'],
    title: 'Cachuela Esperanza: el pueblo de la goma',
    description: 'Excursión desde Riberalta a Cachuela Esperanza, a orillas de los rápidos del río Beni, donde la Casa Suárez manejó el auge de la goma a inicios del siglo XX. Recorremos las construcciones de la época y el paisaje de la cachuela.',
    includes: 'Transporte, guía, almuerzo.', excludes: 'Repelente.',
    minutes: 480, label: 'Día completo', price: 320, start: '07:30:00', slots: 12,
    img: ['Cachuela Esperanza'],
  },
]

// items: e = key de experiencia del MISMO proveedor; d = ítem descriptivo [título, descripción].
export const PACKAGES = [
  {
    key: 'pkg-bolivia-esencial', provider: 'altura', city: 'La Paz', cats: ['NA', 'CU'],
    title: 'Bolivia esencial: La Paz y el Salar (4 días)', // paquete demo previo, reutilizado
    description: 'Cuatro días para conocer lo esencial del altiplano: La Paz desde el aire y el Valle de la Luna, el sitio arqueológico de Tiwanaku y un día completo en el Salar de Uyuni con la Isla Incahuasi.',
    conditions: 'Cupos limitados. Incluye bus cama La Paz–Uyuni. Cancelación sin costo hasta 72 horas antes de la salida.',
    days: 4, price: 2400, slots: 8,
    items: [
      { day: 1, e: 'lpz-teleferico' }, { day: 1, e: 'lpz-valle-luna' },
      { day: 2, e: 'lpz-tiwanaku' },
      { day: 3, d: ['Traslado La Paz → Uyuni', 'Tarde libre en La Paz y bus nocturno cama hacia Uyuni.'] },
      { day: 4, e: 'uyu-incahuasi' },
    ],
    imgFrom: ['uyu-atardecer', 'lpz-tiwanaku'],
  },
  {
    key: 'pkg-altiplano', provider: 'altura', city: 'La Paz', cats: ['AV', 'HI'],
    title: 'Altiplano de altura: Chacaltaya, Tiwanaku y Oruro (3 días)',
    description: 'Un recorrido por el altiplano paceño y orureño: la cumbre del Chacaltaya, las ruinas de Tiwanaku y el Santuario del Socavón en Oruro, con traslado por carretera.',
    conditions: 'Requiere al menos dos noches previas de aclimatación en La Paz. Cancelación sin costo hasta 72 horas antes.',
    days: 3, price: 1350, slots: 10,
    items: [
      { day: 1, e: 'lpz-chacaltaya' },
      { day: 2, e: 'lpz-tiwanaku' },
      { day: 3, d: ['Traslado La Paz → Oruro', 'Salida temprano por carretera hacia Oruro (unas 3 horas).'] },
      { day: 3, e: 'oru-socavon' },
    ],
    imgFrom: ['lpz-chacaltaya', 'oru-socavon'],
  },
  {
    key: 'pkg-uyuni', provider: 'altura', city: 'Uyuni', cats: ['NA'],
    title: 'Salar de Uyuni de día y de noche (2 días)',
    description: 'Dos días en Uyuni: el cementerio de trenes, el atardecer y el cielo estrellado del salar, y al día siguiente el cruce completo hasta la Isla Incahuasi.',
    conditions: 'Incluye una noche de alojamiento en Uyuni. En temporada de lluvias el acceso a Incahuasi puede reemplazarse por otra ruta del salar.',
    days: 2, price: 1650, slots: 8,
    items: [
      { day: 1, e: 'uyu-trenes' }, { day: 1, e: 'uyu-atardecer' }, { day: 1, e: 'uyu-estrellas' },
      { day: 2, e: 'uyu-incahuasi' },
    ],
    imgFrom: ['uyu-incahuasi', 'uyu-trenes'],
  },
  {
    key: 'pkg-titicaca-yungas', provider: 'lagoyungas', city: 'Copacabana', cats: ['NA', 'CU'],
    title: 'Del Titicaca a los Yungas (4 días)',
    description: 'Del lago sagrado de los Andes a la selva de montaña: Copacabana y la Isla del Sol, y después Coroico, con su cerro Uchumachi y la comunidad afroboliviana de Tocaña.',
    conditions: 'Incluye alojamiento y traslados Copacabana → La Paz → Coroico. Cancelación sin costo hasta 72 horas antes.',
    days: 4, price: 1500, slots: 10,
    items: [
      { day: 1, e: 'cop-calvario' },
      { day: 2, e: 'cop-isla-sol' },
      { day: 3, d: ['Traslado a Coroico', 'Viaje por carretera de Copacabana a Coroico pasando por La Paz.'] },
      { day: 4, e: 'cor-uchumachi' }, { day: 4, e: 'cor-tocana' },
    ],
    imgFrom: ['cop-isla-sol', 'cor-uchumachi'],
  },
  {
    key: 'pkg-potosi-tupiza', provider: 'surandino', city: 'Potosí', cats: ['HI', 'NA'],
    title: 'Villa Imperial y quebradas de Tupiza (4 días)',
    description: 'La historia de la plata en Potosí y los paisajes rojos de Tupiza: Casa de Moneda, Cerro Rico, el Cañón del Duende y la Quebrada de Palala.',
    conditions: 'Incluye alojamiento y traslado Potosí → Tupiza. La visita a la mina es opcional y puede reemplazarse por el Ojo del Inca.',
    days: 4, price: 1700, slots: 8,
    items: [
      { day: 1, e: 'pot-moneda' }, { day: 1, e: 'pot-colonial' },
      { day: 2, e: 'pot-cerro-rico' },
      { day: 3, d: ['Traslado Potosí → Tupiza', 'Carretera hacia el sur (unas 4 horas) y tarde en el Cañón del Duende.'] },
      { day: 3, e: 'tup-duende' },
      { day: 4, e: 'tup-palala' },
    ],
    imgFrom: ['pot-moneda', 'tup-palala'],
  },
  {
    key: 'pkg-cochabamba', provider: 'llajta', city: 'Cochabamba', cats: ['CU', 'GA'],
    title: 'Cochabamba: valle, mercado y sabores (3 días)',
    description: 'Tres días en la llajta: el Cristo de la Concordia y el Palacio Portales, La Cancha y la ruta gastronómica, y la subida a las ruinas incas de Inkarakay.',
    conditions: 'Incluye alojamiento en Cochabamba. Cancelación sin costo hasta 48 horas antes.',
    days: 3, price: 950, slots: 12,
    items: [
      { day: 1, e: 'cbba-portales' }, { day: 1, e: 'cbba-cristo' },
      { day: 2, e: 'cbba-cancha' }, { day: 2, e: 'cbba-sabores' },
      { day: 3, e: 'sip-inkarakay' },
    ],
    imgFrom: ['cbba-cristo', 'cbba-portales'],
    weekdays: [2, 3, 4],
  },
  {
    key: 'pkg-torotoro', provider: 'llajta', city: 'Torotoro', cats: ['NA', 'AV'],
    title: 'Torotoro, tierra de dinosaurios (3 días)',
    description: 'Tres días en el Parque Nacional Torotoro: huellas de dinosaurio, el cañón y El Vergel, la caverna de Umajalanta y la Ciudad de Itas.',
    conditions: 'Incluye traslado Cochabamba ↔ Torotoro y alojamiento. El camino puede demorar en temporada de lluvias.',
    days: 3, price: 1100, slots: 10,
    items: [
      { day: 1, d: ['Traslado Cochabamba → Torotoro', 'Salida temprano (unas 4 a 5 horas de viaje).'] },
      { day: 1, e: 'tor-huellas' },
      { day: 2, e: 'tor-umajalanta' },
      { day: 3, e: 'tor-itas' },
    ],
    imgFrom: ['tor-huellas', 'tor-itas'],
  },
  {
    key: 'pkg-tropico', provider: 'llajta', city: 'Villa Tunari', cats: ['AV', 'NA'],
    title: 'Trópico de Cochabamba: Villa Tunari (2 días)',
    description: 'Fin de semana en el trópico: rafting en el río Espíritu Santo, los senderos del Parque Machía y las cavernas de los guácharos en el Parque Carrasco.',
    conditions: 'Incluye traslado desde Cochabamba y una noche de alojamiento. Rafting sujeto al nivel del río.',
    days: 2, price: 900, slots: 8,
    items: [
      { day: 1, e: 'vt-machia' }, { day: 1, e: 'vt-repechon' },
      { day: 2, e: 'vt-rafting' },
    ],
    imgFrom: ['vt-rafting', 'vt-machia'],
    weekdays: [6],
  },
  {
    key: 'pkg-sucre', provider: 'charcas', city: 'Sucre', cats: ['HI', 'CU'],
    title: 'Sucre patrimonial y Tarabuco (3 días)',
    description: 'La capital histórica de Bolivia en tres días: la Ciudad Blanca y la Casa de la Libertad, Cal Orck\'o y el mirador de La Recoleta, y el mercado dominical de Tarabuco.',
    conditions: 'Salidas los viernes para llegar a Tarabuco en domingo. Incluye alojamiento en Sucre.',
    days: 3, price: 1100, slots: 12,
    items: [
      { day: 1, e: 'suc-ciudad-blanca' }, { day: 1, e: 'suc-libertad' },
      { day: 2, e: 'suc-cal-orcko' }, { day: 2, e: 'suc-recoleta' },
      { day: 3, e: 'suc-tarabuco' },
    ],
    imgFrom: ['suc-ciudad-blanca', 'suc-tarabuco'],
    weekdays: [5],
  },
  {
    key: 'pkg-tarija', provider: 'chapaca', city: 'Tarija', cats: ['GA', 'NA'],
    title: 'Tarija entre viñedos y cascadas (3 días)',
    description: 'La Tarija chapaca en tres días: su centro histórico y su cocina, la ruta del vino de altura del Valle de la Concepción y las pozas de Coimata.',
    conditions: 'Incluye alojamiento. Catas sólo para mayores de 18 años. Cancelación sin costo hasta 72 horas antes.',
    days: 3, price: 1250, slots: 12,
    items: [
      { day: 1, e: 'tja-ciudad' }, { day: 1, e: 'tja-sabores' },
      { day: 2, e: 'tja-vino' },
      { day: 3, e: 'tja-coimata' },
    ],
    imgFrom: ['tja-vino', 'tja-coimata'],
  },
  {
    key: 'pkg-samaipata', provider: 'curichi', city: 'Samaipata', cats: ['HI', 'NA'],
    title: 'Samaipata y Amboró (3 días)',
    description: 'Los valles cruceños: El Fuerte de Samaipata, los helechos gigantes del Amboró y las cascadas de Las Cuevas, con base en el pueblo de Samaipata.',
    conditions: 'Incluye traslado desde Santa Cruz y alojamiento en Samaipata. Cancelación sin costo hasta 72 horas antes.',
    days: 3, price: 1300, slots: 10,
    items: [
      { day: 1, d: ['Traslado Santa Cruz → Samaipata', 'Carretera antigua a Cochabamba (unas 3 horas).'] },
      { day: 1, e: 'sam-fuerte' },
      { day: 2, e: 'sam-helechos' },
      { day: 3, e: 'sam-cuevas' },
    ],
    imgFrom: ['sam-fuerte', 'sam-helechos'],
  },
  {
    key: 'pkg-chiquitos', provider: 'curichi', city: 'San Ignacio de Velasco', cats: ['HI', 'CU'],
    title: 'Misiones jesuíticas de Chiquitos (3 días)',
    description: 'Las misiones de Velasco, Patrimonio de la Humanidad: San Ignacio, Santa Ana, San Miguel y San Rafael, con la laguna Guapomó al atardecer.',
    conditions: 'Incluye traslado Santa Cruz → San Ignacio y alojamiento. Los templos son lugares de culto activos.',
    days: 3, price: 1600, slots: 12,
    items: [
      { day: 1, d: ['Traslado Santa Cruz → San Ignacio de Velasco', 'Viaje por carretera a la Chiquitanía.'] },
      { day: 1, e: 'siv-guapomo' },
      { day: 2, e: 'siv-san-miguel' },
      { day: 3, e: 'siv-santa-ana' },
    ],
    imgFrom: ['siv-san-miguel', 'siv-santa-ana'],
  },
  {
    key: 'pkg-rurrenabaque', provider: 'jichi', city: 'Rurrenabaque', cats: ['NA', 'AV'],
    title: 'Rurrenabaque: selva y pampas (3 días)',
    description: 'La Amazonía boliviana en tres días: el río Beni frente a Rurrenabaque, un día de selva en el Madidi y otro en las pampas del Yacuma.',
    conditions: 'Incluye alojamiento en Rurrenabaque. Vacuna contra la fiebre amarilla recomendada.',
    days: 3, price: 1500, slots: 10,
    items: [
      { day: 1, e: 'rur-rio-beni' },
      { day: 2, e: 'rur-madidi' },
      { day: 3, e: 'rur-pampas' },
    ],
    imgFrom: ['rur-madidi', 'rur-pampas'],
  },
]

// Fechas: semanal hasta fin de diciembre y quincenal hasta fines de marzo (≈6 meses de catálogo).
export const SCHEDULE = {
  from: '2026-09-21',
  weeklyUntil: '2026-12-31',
  until: '2027-03-31',
  packageEveryDays: 21,
}
