// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurisClick.Api.Infrastructure.Database;

#nullable disable

namespace TurisClick.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TurisClickDbContext))]
    partial class TurisClickDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurisClick.Api.Modules.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_provider_has_company", "(role = 'PROVIDER' AND company_id IS NOT NULL) OR (role <> 'PROVIDER' AND company_id IS NULL)");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Categories.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Companies.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LegalDocument")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("legal_document");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING_APPROVAL")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("LegalDocument")
                        .IsUnique()
                        .HasDatabaseName("uq_companies_legal_document");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_companies_status");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Destinations.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_destinations_parent_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_destinations_type");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_destinations_name_type_root")
                        .HasFilter("parent_id IS NULL");

                    b.HasIndex("Name", "ParentId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_destinations_name_parent_type")
                        .HasFilter("parent_id IS NOT NULL");

                    b.ToTable("destinations", null, t =>
                        {
                            t.HasCheckConstraint("ck_destinations_country_no_parent", "(type = 'COUNTRY' AND parent_id IS NULL) OR (type <> 'COUNTRY' AND parent_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("DurationLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("duration_label");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExcludesText")
                        .HasColumnType("text")
                        .HasColumnName("excludes_text");

                    b.Property<string>("IncludesText")
                        .HasColumnType("text")
                        .HasColumnName("includes_text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_experiences_company_id");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_experiences_destination_id");

                    b.HasIndex("Status", "DestinationId")
                        .HasDatabaseName("ix_experiences_status_destination");

                    b.ToTable("experiences", null, t =>
                        {
                            t.HasCheckConstraint("ck_experiences_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_experiences_duration", "duration_minutes IS NULL OR duration_minutes > 0");

                            t.HasCheckConstraint("ck_experiences_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.ExperienceAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<int>("ReservedSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_slots");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer")
                        .HasColumnName("total_slots");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExperienceId", "Date" }, "ix_experience_availabilities_experience_date");

                    b.HasIndex(new[] { "ExperienceId", "Date" }, "ux_experience_availabilities_fullday")
                        .IsUnique()
                        .HasFilter("start_time IS NULL");

                    b.HasIndex(new[] { "ExperienceId", "Date", "StartTime" }, "ux_experience_availabilities_timed")
                        .IsUnique()
                        .HasFilter("start_time IS NOT NULL");

                    b.ToTable("experience_availabilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_experience_availabilities_slots", "total_slots > 0 AND reserved_slots >= 0 AND reserved_slots <= total_slots");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.ExperienceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExperienceId" }, "ix_experience_images_experience_id");

                    b.HasIndex(new[] { "ExperienceId" }, "ux_experience_images_one_cover")
                        .IsUnique()
                        .HasFilter("is_cover = true");

                    b.ToTable("experience_images", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ConditionsText")
                        .HasColumnType("text")
                        .HasColumnName("conditions_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_packages_company_id");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_packages_destination_id");

                    b.HasIndex("Status", "DestinationId")
                        .HasDatabaseName("ix_packages_status_destination");

                    b.ToTable("packages", null, t =>
                        {
                            t.HasCheckConstraint("ck_packages_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_packages_duration", "duration_days > 0");

                            t.HasCheckConstraint("ck_packages_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<int>("ReservedSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_slots");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer")
                        .HasColumnName("total_slots");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PackageId", "DepartureDate" }, "ix_package_availabilities_package_date");

                    b.HasIndex(new[] { "PackageId", "DepartureDate" }, "uq_package_availabilities_departure")
                        .IsUnique();

                    b.ToTable("package_availabilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_package_availabilities_slots", "total_slots > 0 AND reserved_slots >= 0 AND reserved_slots <= total_slots");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PackageId" }, "ix_package_images_package_id");

                    b.HasIndex(new[] { "PackageId" }, "ux_package_images_one_cover")
                        .IsUnique()
                        .HasFilter("is_cover = true");

                    b.ToTable("package_images", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId")
                        .HasDatabaseName("ix_package_items_experience_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_package_items_package_id");

                    b.ToTable("package_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_package_items_day", "day_number >= 1");

                            t.HasCheckConstraint("ck_package_items_descriptive_title", "kind <> 'DESCRIPTIVE' OR title IS NOT NULL");

                            t.HasCheckConstraint("ck_package_items_kind_shape", "(kind = 'EXPERIENCE_REFERENCE' AND experience_id IS NOT NULL) OR (kind = 'DESCRIPTIVE' AND experience_id IS NULL)");
                        });
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Reservations.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AiItineraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_itinerary_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING_PAYMENT")
                        .HasColumnName("status");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uuid")
                        .HasColumnName("tourist_id");

                    b.HasKey("Id");

                    b.HasIndex("AiItineraryId")
                        .HasDatabaseName("ix_reservations_ai_itinerary_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reservations_status");

                    b.HasIndex("TouristId")
                        .HasDatabaseName("ix_reservations_tourist_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Reservations.Entities.ReservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<Guid?>("ExperienceAvailabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_availability_id");

                    b.Property<Guid?>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid?>("PackageAvailabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_availability_id");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("product_type");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING_PAYMENT")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("Travelers")
                        .HasColumnType("integer")
                        .HasColumnName("travelers");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceAvailabilityId")
                        .HasDatabaseName("ix_reservation_items_experience_availability");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("PackageAvailabilityId")
                        .HasDatabaseName("ix_reservation_items_package_availability");

                    b.HasIndex("PackageId");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservation_items_reservation_id");

                    b.HasIndex(new[] { "CompanyId", "Status" }, "ix_reservation_items_company_status");

                    b.ToTable("reservation_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservation_items_amounts", "unit_price >= 0 AND subtotal >= 0");

                            t.HasCheckConstraint("ck_reservation_items_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_reservation_items_product_shape", "(product_type = 'EXPERIENCE' AND experience_id IS NOT NULL AND package_id IS NULL AND experience_availability_id IS NOT NULL AND package_availability_id IS NULL) OR (product_type = 'PACKAGE' AND package_id IS NOT NULL AND experience_id IS NULL AND package_availability_id IS NOT NULL AND experience_availability_id IS NULL)");

                            t.HasCheckConstraint("ck_reservation_items_travelers", "travelers > 0");
                        });
                });

            modelBuilder.Entity("experience_categories", b =>
                {
                    b.Property<Guid>("experience_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("experience_id", "category_id");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_experience_categories_category_id");

                    b.ToTable("experience_categories", (string)null);
                });

            modelBuilder.Entity("package_categories", b =>
                {
                    b.Property<Guid>("package_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.HasKey("package_id", "category_id");

                    b.HasIndex("category_id")
                        .HasDatabaseName("ix_package_categories_category_id");

                    b.ToTable("package_categories", (string)null);
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Auth.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Auth.Entities.User", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Companies.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Companies.Entities.Company", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Auth.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Destinations.Entities.Destination", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Destinations.Entities.Destination", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.Experience", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Companies.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurisClick.Api.Modules.Destinations.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.ExperienceAvailability", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.Experience", "Experience")
                        .WithMany("Availabilities")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.ExperienceImage", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.Experience", "Experience")
                        .WithMany("Images")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.Package", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Companies.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurisClick.Api.Modules.Destinations.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageAvailability", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.Package", "Package")
                        .WithMany("Availabilities")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageImage", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.Package", "Package")
                        .WithMany("Images")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.PackageItem", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.Package", "Package")
                        .WithMany("Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Reservations.Entities.Reservation", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Auth.Entities.User", "Tourist")
                        .WithMany()
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Reservations.Entities.ReservationItem", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Companies.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.ExperienceAvailability", "ExperienceAvailability")
                        .WithMany()
                        .HasForeignKey("ExperienceAvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.PackageAvailability", "PackageAvailability")
                        .WithMany()
                        .HasForeignKey("PackageAvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurisClick.Api.Modules.Reservations.Entities.Reservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Experience");

                    b.Navigation("ExperienceAvailability");

                    b.Navigation("Package");

                    b.Navigation("PackageAvailability");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("experience_categories", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Categories.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurisClick.Api.Modules.Experiences.Entities.Experience", null)
                        .WithMany()
                        .HasForeignKey("experience_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("package_categories", b =>
                {
                    b.HasOne("TurisClick.Api.Modules.Categories.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurisClick.Api.Modules.Packages.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("package_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Auth.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Companies.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Destinations.Entities.Destination", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Experiences.Entities.Experience", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Packages.Entities.Package", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Images");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TurisClick.Api.Modules.Reservations.Entities.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
